[versions]
agp = "8.9.3"
hilt = "2.57.2"
commonsIo = "2.18.0"
desugar_jdk_libs_nio = "2.1.5"
gson = "2.13.2"
isoparser = "1.0.6"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lombok = "1.18.38"
material = "1.13.0"
media3Exoplayer = "1.9.1"
mockito = "5.8.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
media = "1.7.1"
newpipeextractor = "17d6e5c5afb7e30506c5f809e96d68ef43f2f31c"
photoview = "2.0.0"
picasso = "2.8"
swiperefreshlayout = "1.2.0"
webkit = "1.15.0"
okhttp = "5.3.2"
okio = "3.16.4"
recyclerview = "1.4.0"

[libraries]
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
desugar_jdk_libs_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs_nio" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
isoparser = { module = "com.googlecode.mp4parser:isoparser", version.ref = "isoparser" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3Exoplayer" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media = { module = "androidx.media:media", version.ref = "media" }
newpipeextractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version.ref = "newpipeextractor" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version = "1.1.0" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
